services:
  drupal:
    image: drupal:10-apache
    ports:
      - 8080:80
    entrypoint: ["/init-drupal.sh"]
    volumes:
      # change the relative path on the left of the colon to point to a location where you can store the files.
      # this ensures you keep your files somewhere safe and not on shared computers.
      # do the same thing for the mysql data further down.
      - ./drupal-data/modules:/var/www/html/modules
      - ./drupal-data/profiles:/var/www/html/profiles
      - ./drupal-data/themes:/var/www/html/themes
      - ./drupal-data/sites:/var/www/html/sites
      - ./init-drupal.sh:/init-drupal.sh
    restart: always
    depends_on:
      - mysql
    environment:
      - DRUPAL_DATABASE_HOST=mysql
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USERNAME=drupal
      - DRUPAL_DATABASE_PASSWORD=drupal
    
    
      

  mysql:
    image: mysql:8.0
    container_name: drupal_mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # change the path on the left of the colon to point to a location where you can store the files.
      # this ensures you keep your files somewhere safe and not on shared computers.
      # do the same thing for the drupal data further up.
      - ./drupal-data/mysql:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: drupal_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=drupal
      - PMA_PASSWORD=drupal
    restart: always
    depends_on:
      - mysql


