services:
  drupal:
    image: drupal:10-apache
    ports:
      - 8080:80
    volumes:
      # change the relative path on the left of the colon to point to a location where you can store the files.
      # this ensures you keep your files somewhere safe and not on shared computers.
      # do the same thing for the mysql data further down.
      - ./drupal-data/modules:/var/www/html/modules
      - ./drupal-data/profiles:/var/www/html/profiles
      - ./drupal-data/themes:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - ./drupal-data/sites:/var/www/html/sites
    restart: always
    depends_on:
      - mysql
    environment:
      - DRUPAL_DATABASE_HOST=mysql
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USERNAME=drupal
      - DRUPAL_DATABASE_PASSWORD=drupal

  mysql:
    image: mysql:8.0
    container_name: drupal_mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # change the path on the left of the colon to point to a location where you can store the files.
      # this ensures you keep your files somewhere safe and not on shared computers.
      # do the same thing for the drupal data further up.
      - ./drupal-data/mysql:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: drupal_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=drupal
      - PMA_PASSWORD=drupal
    restart: always
    depends_on:
      - mysql

# Docker volumes (uncomment if you are using local data (not recommended) above)
#volumes:
  #drupal_modules:
  #drupal_profiles:
  #drupal_themes:
  #drupal_sites:
  #db_data:
